---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache2 web server on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
    - name: Start apache service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"  
    - name: install httpd on redhat nodes
      apt:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"   
    - name: start httpd on redhat nodes
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"     