---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache2 web server on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start apache2 service on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Install httpd on RedHat-based systems
      dnf:
        name: httpd
        state: present
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Start httpd service on RedHat-based systems
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family in ["RedHat", "Amazon"]
